### ISSUE TITLE
-h does not work

### ISSUE THREAD

**Issue by Entze** [rpdelaney/python-chess-annotator#13]
Starting the script with `-h` as argument gives the following traceback:
(I have anonymized the paths with `...`)
```
Traceback (most recent call last):
  File ".../python-chess-annotator/annotator/__main__.py", line 759, in <module>
    main()
  File ".../python-chess-annotator/annotator/__main__.py", line 735, in main
    args = parse_args()
  File ".../python-chess-annotator/annotator/__main__.py", line 57, in parse_args
    return parser.parse_args()
  File "/usr/lib/python3.5/argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1964, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.5/argparse.py", line 1904, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1016, in __call__
    parser.print_help()
  File "/usr/lib/python3.5/argparse.py", line 2358, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.5/argparse.py", line 2342, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.5/argparse.py", line 278, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.5/argparse.py", line 208, in format_help
    func(*args)
  File "/usr/lib/python3.5/argparse.py", line 208, in format_help
    func(*args)
  File "/usr/lib/python3.5/argparse.py", line 515, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python3.5/argparse.py", line 602, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character ')' (0x29) at index 50
```

the other parsing options work though.

**Comment by rpdelaney** [comment]
Thanks, this is now fixed in master and will be corrected in the next release.

**Comment by Entze** [comment]
I too could verify that it works.
